name: Test JS Project
on:
  workflow_dispatch: # manually triggered
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # print useful informtion
      - run: pwd
      - run: ls
      - run: node -v
      - run: npm -v

      - name: Install dependencies
        run: npm install

      - name: Unit test
        run: npm test
